//! Kiwi Farms' site-wide smiley/emote table, scraped from https://kiwifarms.st/help/smilies/
//! (a live browser session, since the reference page lazy-loads several rows via
//! CSS background-image rather than a plain <img src>, and the anonymous JSON
//! upload/API endpoints this project already reverse-engineers elsewhere don't cover
//! this at all - there's no public API, just the rendered page itself).
//!
//! The images themselves are bundled with the client under its own
//! sneedchat-smilies/ resource directory (which the client resolves against its
//! own install root - see the listSneedchatSmilies RPC) rather than fetched from
//! kiwifarms.st at runtime - deliberate: this table is static and small (~1.8MB
//! total), so there's no reason to depend on a live Tor-routed fetch (and its
//! failure modes) just to show something this project already has a permanent,
//! correct copy of.

pub struct Smilie {
    pub label: &'static str,
    /// Filename within sneedchat-smilies/ (relative to the client's own
    /// resource directory, not this crate's) - not a URL or a path on disk
    /// nobilis itself resolves; the client builds the actual URL.
    pub file: &'static str,
    /// Every shortcode that triggers this smilie (site rendering treats them as
    /// interchangeable aliases of the same image) - confirmed none collide across
    /// the full 175-entry table.
    pub aliases: &'static [&'static str],
}

pub const SMILIES: &[Smilie] = &[
    Smilie { label: "Smile", file: "styles_custom_emotes_svg_chris-smile.svg", aliases: &[":)", ":happy:", ":smile:"] },
    Smilie { label: "Big Grin", file: "styles_custom_emotes_svg_chris-bigsmile.svg", aliases: &[":biggrin:", ":D", ":-D"] },
    Smilie { label: "Wink", file: "styles_custom_emotes_svg_chris-wink.svg", aliases: &[";)", ";-)", ":wink:"] },
    Smilie { label: "Lol", file: "styles_custom_emotes_svg_chris-laugh.svg", aliases: &[":lol:"] },
    Smilie { label: "Lit", file: "styles_custom_emotes_svg_chris-lit.svg", aliases: &[":lit:"] },
    Smilie { label: "Razz", file: "styles_custom_emotes_svg_chris-razz.svg", aliases: &[":P", ":razz:"] },
    Smilie { label: "Stress Sigh", file: "styles_custom_emotes_svg_chris-sigh.svg", aliases: &["*sigh*", "*SIGH*", ":sigh:"] },
    Smilie { label: "Rolling Eyes", file: "styles_custom_emotes_svg_chris-roll.svg", aliases: &[":roll:"] },
    Smilie { label: "Confused", file: "styles_custom_emotes_svg_chris-confused.svg", aliases: &[":\\", ":confused:"] },
    Smilie { label: "Surprised", file: "styles_custom_emotes_svg_chris-surprised.svg", aliases: &[":O", ":surprised:"] },
    Smilie { label: "Embarassed", file: "styles_custom_emotes_svg_chris-embarassed.svg", aliases: &[":oops:", ":blush:"] },
    Smilie { label: "Christine", file: "styles_custom_emotes_svg_chris-christine.svg", aliases: &[":christine:"] },
    Smilie { label: "Sad", file: "styles_custom_emotes_svg_chris-sad.svg", aliases: &[":(", ":sad:"] },
    Smilie { label: "Cringe", file: "styles_custom_emotes_svg_chris-cringe.svg", aliases: &[":cringe:"] },
    Smilie { label: "Mad", file: "styles_custom_emotes_svg_chris-mad.svg", aliases: &[":mad:", ">:(", ":@"] },
    Smilie { label: "Eek", file: "styles_custom_emotes_svg_chris-eek.svg", aliases: &[":o", ":eek:", ":shock:", ":shocked:"] },
    Smilie { label: "Evil", file: "styles_custom_emotes_svg_chris-evil.svg", aliases: &[":evil:", ">:)"] },
    Smilie { label: "Unholy", file: "styles_custom_emotes_svg_chris-unholy.svg", aliases: &[":unholy:", ":unholey:"] },
    Smilie { label: "Twisted", file: "styles_custom_emotes_svg_chris-twisted.svg", aliases: &[":twisted:"] },
    Smilie { label: "Punished", file: "styles_custom_emotes_svg_chris-punished.svg", aliases: &[":punished:"] },
    Smilie { label: "Neutral", file: "styles_custom_emotes_svg_chris-neutral.svg", aliases: &[":|", ":neutral:", ":meh:"] },
    Smilie { label: "Cool", file: "styles_custom_emotes_svg_chris-cool.svg", aliases: &[":cool:"] },
    Smilie { label: "Geek", file: "styles_custom_emotes_svg_chris-nerd.svg", aliases: &[":geek:", ":nerd:"] },
    Smilie { label: "Crying", file: "styles_custom_emotes_svg_chris-tears.svg", aliases: &[":'(", ":cry:"] },
    Smilie { label: "Crying Blood", file: "styles_custom_emotes_svg_chris-cryblood.svg", aliases: &[":cryblood:"] },
    Smilie { label: "Question", file: "styles_custom_emotes_svg_question.svg", aliases: &[":?:"] },
    Smilie { label: "Exclaim", file: "styles_custom_emotes_svg_exclamation.svg", aliases: &[":!:"] },
    Smilie { label: "Crashing into Slumber", file: "styles_custom_emotes_svg_chris-slumber.svg", aliases: &["(:_("] },
    Smilie { label: "Haters to the Left", file: "styles_default_xenforo_smilies_phpbb_icon_left.gif", aliases: &[":left:"] },
    Smilie { label: "Horse Face", file: "styles_default_xenforo_smilies_phpbb_icon_horse_face.gif", aliases: &[":c", ":C"] },
    Smilie { label: "Heart Empty", file: "styles_custom_emoji_Lovequest_200_202025.svg", aliases: &[":heart-empty:"] },
    Smilie { label: "Heart Full", file: "styles_custom_emoji_Lovequest_20100_202025.svg", aliases: &[":heart-full:"] },
    Smilie { label: "Ow.", file: "styles_custom_emotes_ow.gif", aliases: &[":ow:", ":rake:", ":amish:"] },
    Smilie { label: "Hi A-Log!", file: "styles_default_xenforo_smilies_phpbb_icon_alog.gif", aliases: &[":alog:", ":nice bloke:"] },
    Smilie { label: "Hi Anna!", file: "styles_default_xenforo_smilies_phpbb_icon_anna.gif", aliases: &[":anna:"] },
    Smilie { label: "Asperchu", file: "styles_default_xenforo_smilies_phpbb_icon_asperchu.png", aliases: &[":asperchu:"] },
    Smilie { label: "Sighduck", file: "styles_default_xenforo_smilies_phpbb_icon_sighduck.gif", aliases: &[":sighduck:"] },
    Smilie { label: "Snorlax", file: "styles_default_xenforo_smilies_phpbb_icon_snorlax.gif", aliases: &[":snorlax:"] },
    Smilie { label: "Squirtle", file: "styles_default_xenforo_smilies_phpbb_icon_squirtle.gif", aliases: &["*yawn*", "*YAWN*", ":squirtle:"] },
    Smilie { label: "Sonichu", file: "styles_default_xenforo_smilies_phpbb_icon_sonichu.png", aliases: &[":sonichu:"] },
    Smilie { label: "Dang, Dirty Troll", file: "styles_default_xenforo_smilies_phpbb_icon_troll.gif", aliases: &["}:P"] },
    Smilie { label: "Pickleman", file: "styles_default_xenforo_smilies_phpbb_icon_pickleman.gif", aliases: &[":pickleman:"] },
    Smilie { label: "Julay", file: "styles_default_xenforo_smilies_phpbb_icon_julay.png", aliases: &[":julay:"] },
    Smilie { label: "Ween", file: "styles_default_xenforo_smilies_phpbb_icon_ween.gif", aliases: &[":epik:", ":ween:", ":cool guy:", ":weensvg:"] },
    Smilie { label: "Stupid", file: "styles_default_xenforo_smilies_phpbb_icon_poll.png", aliases: &[":stupid:"] },
    Smilie { label: "Stressed", file: "styles_default_xenforo_smilies_phpbb_icon_stressed.png", aliases: &["|:("] },
    Smilie { label: "Sonichu Medallion", file: "styles_default_xenforo_smilies_phpbb_icon_medallion.gif", aliases: &[":medallion:"] },
    Smilie { label: "Q-Sand", file: "styles_default_xenforo_smilies_phpbb_icon_qsand.gif", aliases: &[":qsand:"] },
    Smilie { label: "Pickle", file: "styles_default_xenforo_smilies_phpbb_icon_pickle.gif", aliases: &[":pickle:"] },
    Smilie { label: "Fapcup", file: "styles_default_xenforo_smilies_phpbb_icon_fapcup.gif", aliases: &[":fapcup:"] },
    Smilie { label: "DIRTY, CRAPPED BRIEFS", file: "styles_default_xenforo_smilies_phpbb_icon_briefs.gif", aliases: &[":briefs:"] },
    Smilie { label: "Tomgirl", file: "styles_default_xenforo_smilies_phpbb_icon_tomgirl.gif", aliases: &[":tomgirl:"] },
    Smilie { label: "Tugboat", file: "styles_default_xenforo_smilies_phpbb_icon_tugboat.gif", aliases: &[":tugboat:"] },
    Smilie { label: "(Is this thing on? Oh!) Boo hoo hoo ~ !", file: "styles_custom_emotes_crocodile.png", aliases: &[":crocodile:"] },
    Smilie { label: "Analchest Souljer", file: "styles_default_xenforo_smilies_phpbb_icon_tyce.png", aliases: &[":tyceknife:"] },
    Smilie { label: "Eli", file: "styles_custom_emotes_jace_Of1Yvii.png", aliases: &[":eli:"] },
    Smilie { label: "Horses can't even get pussy...", file: "styles_custom_emotes_jace_Uw8NCT5.png", aliases: &[":eli3:"] },
    Smilie { label: "I've unchained the beast within.", file: "styles_custom_emotes_jace_7wA9pXj.png", aliases: &[":tycesuit:"] },
    Smilie { label: "im warier", file: "styles_custom_emotes_jace_ifPazCJ.png", aliases: &[":tyceskullmask:"] },
    Smilie { label: "My blade is a tool of justice.", file: "styles_custom_emotes_jace_uZd19Bc.png", aliases: &[":jaceknife:"] },
    Smilie { label: "Oh baby, a triple!", file: "styles_custom_emotes_jace_0XKIXBh.png", aliases: &[":jacewow:"] },
    Smilie { label: "Press 1", file: "styles_dark_ratings_press_1.png", aliases: &[":1:"] },
    Smilie { label: "Press 2", file: "styles_dark_ratings_press_2.png", aliases: &[":2:"] },
    Smilie { label: "RESPECT ME", file: "styles_custom_emotes_jace_ylo9W2m.png", aliases: &[":jacefedora:"] },
    Smilie { label: "Semper Fidelis to all are armed forces.", file: "styles_custom_emotes_jace_NYuMHTI.png", aliases: &[":semperfidelis:"] },
    Smilie { label: "She's not a dog, she's a WOLF", file: "styles_custom_emotes_jace_a6181SW.png", aliases: &[":soap:"] },
    Smilie { label: "They don't call me Head Shot Jace for nothing.", file: "styles_custom_emotes_jace_CHJMi6Q.png", aliases: &[":stickup:"] },
    Smilie { label: "Wow Dude Its Called Recycling", file: "styles_custom_emotes_jace_2dDorQI.png", aliases: &[":eli2:"] },
    Smilie { label: "WTF Face", file: "styles_custom_emotes_jace_cLeOgy3.png", aliases: &[":jacewtf:"] },
    Smilie { label: "Desert Eagle (Left)", file: "styles_default_xenforo_smilies_phpbb_icon_deagle_left.png", aliases: &[":deagleleft:"] },
    Smilie { label: "Desert Eagle (Right)", file: "styles_default_xenforo_smilies_phpbb_icon_deagle.png", aliases: &[":deagle:", ":deagleright:", ":deserteagle:"] },
    Smilie { label: "Steyr AUG (Left)", file: "styles_default_xenforo_smilies_phpbb_icon_aug_left.png", aliases: &[":augleft:"] },
    Smilie { label: "Steyr AUG (Right)", file: "styles_default_xenforo_smilies_phpbb_icon_aug_right.png", aliases: &[":aug:", ":augright:"] },
    Smilie { label: "Grilled Cheese", file: "styles_default_xenforo_smilies_phpbb_icon_grilledcheese.gif", aliases: &[":csand:", ":grilledcheese:", ":cheese:"] },
    Smilie { label: "Jace", file: "styles_default_xenforo_smilies_phpbb_icon_jace.png", aliases: &[":jace:", ":parkourdude91:", ":tacticool:"] },
    Smilie { label: "#TYCED", file: "styles_default_xenforo_smilies_phpbb_icon_tyced.png", aliases: &["#TYCED"] },
    Smilie { label: "Jace Pout", file: "styles_custom_emotes_jace_oLzPk8e.png", aliases: &[":jacepout:"] },
    Smilie { label: "Reply Button", file: "styles_custom_emotes_post-reply.png", aliases: &[":reply:", ":anom:", ":anominous:"] },
    Smilie { label: "Male", file: "styles_custom_emotes_male.png", aliases: &[":male:", ":gorilla:"] },
    Smilie { label: "Pinetar", file: "styles_custom_emotes_pinetar.png", aliases: &[":pinetar:", ":rape:"] },
    Smilie { label: "Mortal Wombat", file: "styles_custom_emotes_mortal-wombat.png", aliases: &[":wombat:", ":mortalwombat:"] },
    Smilie { label: "Billdozer", file: "styles_default_xenforo_smilies_phpbb_icon_billdozer.gif", aliases: &[":dunsparce:", ":bill:", ":billdozer:"] },
    Smilie { label: "Die, Null", file: "styles_custom_emotes_dienull.gif", aliases: &[":dienull:"] },
    Smilie { label: "Lewd! ... But I like it.", file: "styles_custom_emotes_panda.gif", aliases: &[":panda:", ":lewd:"] },
    Smilie { label: "Applecat", file: "styles_custom_emotes_applecat.webp", aliases: &[":applecat:"] },
    Smilie { label: "Coster", file: "styles_default_xenforo_smilies_phpbb_icon_coster.png", aliases: &[":coster:"] },
    Smilie { label: "Paul Blart", file: "styles_default_xenforo_smilies_phpbb_icon_paulblart.png", aliases: &[":blart:", ":paulblart:"] },
    Smilie { label: "brooklynbailiff", file: "styles_default_xenforo_smilies_phpbb_icon_brooklynbailiff.gif", aliases: &[":bb:", ":brooklynbailiff:"] },
    Smilie { label: "CatParty", file: "styles_default_xenforo_smilies_phpbb_icon_catparty.gif", aliases: &[":catparty:"] },
    Smilie { label: "champthom", file: "styles_default_xenforo_smilies_phpbb_icon_champthom.gif", aliases: &[":champ:", ":champthom:"] },
    Smilie { label: "Drunk Mythos", file: "styles_default_xenforo_smilies_phpbb_icon_boozemythos.png", aliases: &[":drunkmythos:", ":boozemythos:"] },
    Smilie { label: "drunkenhobo", file: "styles_default_xenforo_smilies_phpbb_icon_krystal.png", aliases: &[":hobo:", ":drunkenhobo:", ":dh:"] },
    Smilie { label: "Freecell", file: "styles_default_xenforo_smilies_phpbb_icon_freecell.gif", aliases: &[":freecell:"] },
    Smilie { label: "Hulk Hogan", file: "styles_default_xenforo_smilies_phpbb_icon_hulk.png", aliases: &[":hulk:", ":hulkhogan:", ":hulkster:"] },
    Smilie { label: "Hunger Mythos", file: "styles_default_xenforo_smilies_phpbb_icon_mythos.jpg", aliases: &[":mythos:", ":hungermythos:"] },
    Smilie { label: "KatsuKitty", file: "styles_default_xenforo_smilies_phpbb_icon_katsukitty.gif", aliases: &[":katsu:", ":katsukitty:"] },
    Smilie { label: "The Knife", file: "styles_default_xenforo_smilies_phpbb_icon_knife.gif", aliases: &[":knife:"] },
    Smilie { label: "Glaive", file: "styles_custom_emotes_glaive.png", aliases: &[":glaive:"] },
    Smilie { label: "Melchett", file: "styles_default_xenforo_smilies_phpbb_icon_melchett.gif", aliases: &[":melchett:", ":mel:"] },
    Smilie { label: "Null", file: "styles_custom_emotes_dog.gif", aliases: &[":null:"] },
    Smilie { label: "Dove", file: "styles_default_xenforo_smilies_phpbb_snakesvsplanes.png", aliases: &[":dove:", ":mourningdove:", ":snakes:"] },
    Smilie { label: "silentprincess", file: "styles_default_xenforo_smilies_phpbb_icon_silentprincess.png", aliases: &[":sp:", ":silentprincess:", ":silent:", ":fairy"] },
    Smilie { label: "Smokedaddy", file: "styles_default_xenforo_smilies_phpbb_icon_smokedaddy.gif", aliases: &[":smokedaddy:", ":smoke:"] },
    Smilie { label: "Sunshine Goodness", file: "styles_default_xenforo_smilies_phpbb_icon_sunshine_goodness.png", aliases: &[":sunshinegoodness:", ":sg:", ":luna:"] },
    Smilie { label: "Waifu", file: "styles_default_xenforo_smilies_phpbb_icon_waifu.png", aliases: &[":waifu:", ":faggotnerd:"] },
    Smilie { label: "Waifu Sad", file: "styles_custom_emotes_waifu-sad.png", aliases: &[":sadwaifu:"] },
    Smilie { label: "He is your host, the man they call Ghost.", file: "styles_custom_emotes_ghost.png", aliases: &[":ghost:"] },
    Smilie { label: "WOOOOOOOOOOOOO", file: "styles_custom_emotes_ghost-woo.gif", aliases: &[":woo:"] },
    Smilie { label: "HAH HAH HAAAAAAH", file: "styles_custom_emotes_ghost-laugh.gif", aliases: &[":hah:", ":ghost-laugh:"] },
    Smilie { label: "cans.wav", file: "styles_custom_emotes_cans.gif", aliases: &[":cans:"] },
    Smilie { label: "Johnny Walker, Blue Label, Oh yeaaaa!", file: "styles_custom_emotes_johnny-walker-blue-label-oh-yea.png", aliases: &[":bluelabel:", ":johnny:", ":walker:", ":johnnywalker:"] },
    Smilie { label: "Hambone", file: "styles_custom_emotes_hambone.png", aliases: &[":hambone:"] },
    Smilie { label: "Notice me, Ghost!", file: "styles_custom_emotes_notice-me.gif", aliases: &[":noticeme:"] },
    Smilie { label: "BEEJAMS!", file: "styles_custom_emotes_bj.png", aliases: &[":beejams:"] },
    Smilie { label: "Bogged", file: "styles_custom_emotes_bogged.png", aliases: &[":bogged:"] },
    Smilie { label: "Chicken", file: "styles_custom_emotes_chicken.gif", aliases: &[":chicken:"] },
    Smilie { label: "Cunning Pepe", file: "styles_custom_emotes_cunning-pepe.png", aliases: &[":cunningpepe:"] },
    Smilie { label: "fucking gold", file: "styles_custom_emotes_gold.png", aliases: &[":gold:"] },
    Smilie { label: "Smug", file: "styles_custom_emotes_something-smug.gif", aliases: &[":smug:"] },
    Smilie { label: "Thinking", file: "styles_custom_emotes_thinking-face_1f914.png", aliases: &[":thinking:"] },
    Smilie { label: "Grab", file: "styles_custom_emotes_Grab.png", aliases: &[":grab:"] },
    Smilie { label: "【ｇｕｎｔｗａｖｅ】", file: "styles_custom_emotes_gunt.gif", aliases: &[":gunt:"] },
    Smilie { label: "Filthy Grin", file: "styles_custom_emotes_filthy.gif", aliases: &[":philthy:"] },
    Smilie { label: "Salt", file: "styles_custom_emotes_salt.gif", aliases: &[":salt:"] },
    Smilie { label: "Shit Eating Grin", file: "styles_custom_emotes_shit-eating.jpg", aliases: &[":shit-eating:", ":shiteating:"] },
    Smilie { label: "ARE YOU GUVKING HAPPY?", file: "styles_custom_emotes_spudking.png", aliases: &[":spudking:", ":guvking:"] },
    Smilie { label: "Bernie Cuck", file: "styles_custom_emotes_cuck.png", aliases: &[":cuck:", ":sanders:", ":bernie:", ":suck:"] },
    Smilie { label: "Reality", file: "styles_custom_emotes_reality.png", aliases: &[":reality:"] },
    Smilie { label: "Hillary Clinton", file: "attachments_cunt-png.63843.png", aliases: &[":hillary:", ":shillary:", ":cunt:"] },
    Smilie { label: "Stressing Out", file: "styles_custom_emotes_dsp-stress.png", aliases: &[":stress:", ":stressing:"] },
    Smilie { label: "Wall!", file: "styles_custom_emotes_icon_wall.gif", aliases: &[":wall:"] },
    Smilie { label: "Trump", file: "styles_custom_emotes_trump.png", aliases: &[":trump:"] },
    Smilie { label: "Eyes that scream", file: "styles_custom_emotes_suffering.png", aliases: &[":suffering:"] },
    Smilie { label: "Bork", file: "styles_default_xenforo_smilies_phpbb_icon_bork.png", aliases: &[":bork:"] },
    Smilie { label: "Slayer Gnome", file: "styles_default_xenforo_smilies_phpbb_icon_slayer.png", aliases: &[":slayer:", ":gayer:", ":gnome:"] },
    Smilie { label: "Special Snowflake", file: "styles_default_xenforo_smilies_phpbb_icon_snowflake.gif", aliases: &[":tumblr:", ":tumblrite:", ":snowflake:"] },
    Smilie { label: "Coffee (Left)", file: "styles_default_xenforo_smilies_phpbb_icon_coffee_left.png", aliases: &[":coffeeleft:"] },
    Smilie { label: "Coffee (Right)", file: "styles_default_xenforo_smilies_phpbb_icon_coffee.png", aliases: &[":coffee:", ":coffeeright:"] },
    Smilie { label: "AUGH YEAH", file: "styles_default_xenforo_smilies_phpbb_icon_augh_yeah.png", aliases: &["AUGH YEAH"] },
    Smilie { label: "Neckbeard", file: "styles_default_xenforo_smilies_phpbb_icon_neckbeard.gif", aliases: &[":neckbeard:"] },
    Smilie { label: "Popcorn", file: "styles_default_xenforo_smilies_phpbb_icon_popcorn.gif", aliases: &[":popcorn:"] },
    Smilie { label: "Ruse Cruise", file: "styles_default_xenforo_smilies_phpbb_icon_ruse.png", aliases: &[":ruse:"] },
    Smilie { label: "Sub", file: "styles_default_xenforo_smilies_phpbb_icon_sub.png", aliases: &[":sub:"] },
    Smilie { label: "That's... That's an eggplant!", file: "styles_custom_emotes_eggplant.png", aliases: &[":eggplant:", ":dick:"] },
    Smilie { label: "What a Story!", file: "styles_default_xenforo_smilies_phpbb_icon_story.gif", aliases: &[":story:"] },
    Smilie { label: "StrikerWolf", file: "styles_custom_emotes_striker.webp", aliases: &[":striker:", ":strikerwolf:", ":wolfguy:"] },
    Smilie { label: "wow", file: "styles_default_xenforo_smilies_phpbb_icon_doge_wow.gif", aliases: &[":wow:"] },
    Smilie { label: "gay", file: "styles_custom_emotes_gay.png", aliases: &[":gay:"] },
    Smilie { label: "nice dude!", file: "styles_default_xenforo_smilies_phpbb_icon_nice.gif", aliases: &[":nicedude:"] },
    Smilie { label: "Like", file: "styles_custom_emoji_Like.svg", aliases: &[":like:"] },
    Smilie { label: "Dislike", file: "styles_custom_emoji_Dislike.svg", aliases: &[":dislike:"] },
    Smilie { label: "Agree", file: "styles_custom_emoji_Agree.svg", aliases: &[":agree:"] },
    Smilie { label: "Disagree", file: "styles_custom_emoji_Disagree.svg", aliases: &[":disagree:"] },
    Smilie { label: "Achievement", file: "styles_custom_emoji_Achievement.svg", aliases: &[":achievement:"] },
    Smilie { label: "Null's Love", file: "styles_custom_emoji_Mutt_20Love.svg", aliases: &[":mutted:", ":muttlove:"] },
    Smilie { label: "Winner", file: "styles_custom_emoji_Winner.svg", aliases: &[":winner:"] },
    Smilie { label: "Semper Fidelis", file: "styles_custom_emoji_Semper_20Fidelis.svg", aliases: &[":semperfi:"] },
    Smilie { label: "Informative", file: "styles_custom_emoji_Informative.svg", aliases: &[":informative:"] },
    Smilie { label: "Feels", file: "styles_custom_emoji_Feels.svg", aliases: &[":feels:"] },
    Smilie { label: "Optimistic", file: "styles_custom_emoji_Optimistic.svg", aliases: &[":optimistic:"] },
    Smilie { label: "DRINK", file: "styles_custom_emoji_Drink.svg", aliases: &[":drink:"] },
    Smilie { label: "Lunacy", file: "styles_custom_emoji_Lunacy.svg", aliases: &[":lunacy:", ":lunatic:", "🌙"] },
    Smilie { label: "Political Sperging", file: "styles_custom_emoji_Moai.svg", aliases: &[":politisperg:", ":politicalsperging:", ":politicalsperg:", "🗿"] },
    Smilie { label: "Coom", file: "styles_custom_emotes_dspcoom.png", aliases: &[":coom:", ":dspCoom:"] },
    Smilie { label: "Diddler", file: "styles_custom_emotes_diddler2.png", aliases: &[":diddler:"] },
    Smilie { label: "Fat Pat", file: "styles_custom_emotes_fatpat.png", aliases: &[":tomlinson:", ":fatpat:"] },
    Smilie { label: "Felted", file: "attachments_felted-gif.6203542.gif", aliases: &[":felted:"] },
    Smilie { label: "Nite nite time", file: "attachments_nitenite-gif.6203539.gif", aliases: &[":nitenite:", ":nightnight:"] },
    Smilie { label: "Ramona (formerly Ralph)", file: "attachments_ramona-ralph-png.6203404.png", aliases: &[":ramona:", ":bluehair:"] },
    Smilie { label: "Ratface", file: "styles_custom_emotes_ChantalSmug.png", aliases: &[":ratface:"] },
    Smilie { label: "Really, nigga?", file: "styles_custom_emotes_rekieta_really.webp", aliases: &[":really:"] },
    Smilie { label: "Sorry, Gator!", file: "styles_custom_emotes_gator.webp", aliases: &[":gator:"] },
    Smilie { label: "I can't believe it, I lost it all man!", file: "styles_custom_emotes_bmj_loss.png", aliases: &[":lossmanjack:", ":bossmanjack:", ":bossman:"] },
    Smilie { label: "Juice!", file: "styles_custom_emotes_bmj_juicy.gif", aliases: &[":juice:"] },
    Smilie { label: "Ross, the Destroyer of Juice", file: "styles_custom_emotes_bmj_ross_hq.png", aliases: &[":ross:"] },
];
